### ISSUE TITLE
Display Neovim with a small filetype

### ISSUE THREAD

**Issue by Shatur** [ObserverOfTime/nvimcord#1]
It would be great to display Neovim icon with a small filetype icon as it's done in https://github.com/andweeb/presence.nvim

**Comment by ObserverOfTime** [comment]
Why not use that plugin then?

**Comment by Shatur** [comment]
Causes stuttering when switching buffers. That's important to me.
Your plugin does not have this disadvantage.

**Comment by ObserverOfTime** [comment]
I'll add an option.

**Comment by ObserverOfTime** [comment]
Implemented in 2b82f80.

```lua
require('nvimcord').setup {
  large_file_icon = false,
  ...
}

**Comment by Shatur** [comment]
Thank you a lot!

**Comment by Shatur** [comment]
Hm... `large_file_icon` have no effect for me.
It looks like this:
![изображение](https://github.com/ObserverOfTime/nvimcord/assets/22453358/c65648f1-341e-4077-938f-093f8b1f2824)

**Comment by ObserverOfTime** [comment]
Can't reproduce this one either.

**Comment by Shatur** [comment]
Oh, my bad, I accidentally used an older version. Works like a charm, thank you a lot!
