### ISSUE TITLE
Workspace is always my home directory

### ISSUE THREAD

**Issue by Shatur** [ObserverOfTime/nvimcord#2]
I noticed that my workspace is always my home directory.
But the readme mention `cwd basename`. Is the actual default is different?

**Comment by ObserverOfTime** [comment]
What's the output of `:lua=vim.fn.fnamemodify(vim.loop.cwd(), ':t')` ?

**Comment by Shatur** [comment]
`nvim` (my Neovim configuration folder)

**Comment by Shatur** [comment]
Here is how it looks (should be `Working on nvim`):
![изображение](https://github.com/ObserverOfTime/nvimcord/assets/22453358/82610dff-dd54-4529-89ee-6aa3104789bd)

And here is my configuration:
```lua
require('nvimcord').setup({
  autostart = true,
  log_level = vim.log.levels.WARN,
})
```

**Comment by ObserverOfTime** [comment]
I'll look into it.

**Comment by ObserverOfTime** [comment]
I can't reproduce this issue.

**Comment by Shatur** [comment]
Oh, I think I know why it happens. The plugin doesn't track the change of cwd. I just usually open it in home and my session manager automatically loads the latest working directory.
Try changing working directory using `:cd`, you should be able to see the "issue". Probably it's more of a feature request - track changes of the cwd.

**Comment by ObserverOfTime** [comment]
I won't be able to implement that anytime soon.
Can your session manager set `g:nvimcord#workspace_name` as a workaround for now?

**Comment by Shatur** [comment]
In addition to the session manager, there is also `:cd`. I think proper solution would be to listen for `DirChanged` autocmd.

**Comment by ObserverOfTime** [comment]
I don't want it to change when you cd into a subdirectory of the project.
My plan was to implement workspace detection through git…eventually.

**Comment by Shatur** [comment]
Maybe fallback to cwd if a git repository is not found?

**Comment by ObserverOfTime** [comment]
> Maybe fallback to cwd if a git repository is not found?

Yes, that's part of the plan.

**Comment by ObserverOfTime** [comment]
This autocmd should work for you in the meantime:

```vim
au DirChanged * :let g:nvimcord#workspace_name = fnamemodify(v:event.cwd, ':t')
```

**Comment by Shatur** [comment]
Then tracking for cwd changes should be handy. Later you will just add additional check for a git repo.

**Comment by Shatur** [comment]
> This autocmd should work for you in the meantime:

Okay, will use this in the meantime, thank you!

**Comment by Shatur** [comment]
Looks like changing `g:nvimcord#workspace_name` doesn't have any effect.
Try this:
```vim
let g:nvimcord#workspace_name = 'test'
echo g:nvimcord#workspace_name
```
You will see `test`, but in Discord it still will be your first workspace.

**Comment by ObserverOfTime** [comment]
Does this work? I can't try it at the moment.

 ```lua
vim.api.nvim_create_autocmd('DirChanged', {
    callback = function()
        local Discord = require 'nvimcord.discord'
        Discord.config.workspace_name = vim.fs.basename(vim.v.event.cwd)
    end,
    group = 'nvimcord'
})
```

**Comment by Shatur** [comment]
Yes, this works, thank you!
Small improvement - you can use `event` argument that passed to the callback to obtain the event information instead of inspecting vimscript variable:
```lua
local discord = require('nvimcord.discord')
vim.api.nvim_create_autocmd('DirChanged', {
  callback = function(event) discord.config.workspace_name = vim.fs.basename(event.file) end,
  group = 'nvimcord',
})
```

**Comment by ObserverOfTime** [comment]
Can you try the [`workspace`](https://github.com/ObserverOfTime/nvimcord/tree/workspace) branch? @Shatur @Cyuria 
Set `dynamic_workspace = true` to enable the autocmd.

**Comment by Shatur** [comment]
I have the following error:
```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: ...m/pack/plugins/start/nvimcord/lua/nvimcord/workspace.lua:5: attempt to call field 'system' (a nil value)
stack traceback:
	...m/pack/plugins/start/nvimcord/lua/nvimcord/workspace.lua:5: in function 'workspace_url'
	...config/nvim/pack/plugins/start/nvimcord/lua/nvimcord.lua:84: in function 'start'
	...config/nvim/pack/plugins/start/nvimcord/lua/nvimcord.lua:130: in function <...config/nvim/pack/plugins/start/nvimcord/lua/nvimcord.lua:129>
```

**Comment by ObserverOfTime** [comment]
You need Neovim nightly now. I won't merge it into master until v0.10 is released.
